name: ci


on: [push, pull_request]

jobs:
  build macOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: brew install autoconf automake libtool shunit2
    - name: build
      run: ./build.sh
    - name: sudo make install
      run: sudo make install
    - name: make distclean
      run: make distclean
      
  build Linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: if ! clang-10 --version -v COMMAND &> /dev/null \
           then \
           echo "Please, install clang." \
           fi
