name: ci


on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: brew install autoconf automake libtool shunit2
    - name: build
      run: ./build.sh
    - name: sudo make install
      run: sudo make install
    - name: make distclean
      run: make distclean
